/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gajzuzgglelbhgjueuag"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhanp1emdnbGVsYmhnanVldWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4ODYzNjEsImV4cCI6MjA3NTQ2MjM2MX0.yA_Bd-SG6uwVZqKJeEMRAlJ55E-6zWX0QzD5cljBtdo"